[package]
authors = ["Alexander Antonio Gonzalez Fertel"]
version = "0.1.0"
name = "bulloak"
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/alexfertel/bulloak"
homepage = "https://github.com/alexfertel/bulloak"
documentation = "https://github.com/alexfertel/bulloak"
description = """
A simple, fast, and easy to use Solidity test generator based on
the Branching Tree Technique.
"""
keywords = ["solidity", "testing", "branching-tree-technique", "cli"]
categories = ["development-tools::testing", "command-line-utilities", "compilers", "parsing"]
exclude = ["/.github/*"]

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
indexmap = "2.0.0"

[dev-dependencies]
pretty_assertions = { version= "1.4.0" }
